//prettier-ignore
export const WellKnownCryptoAssets = [
    ["armm-v3-usdc", "RealT RMM V3 USDC", "armmv3USDC", 6, { coingeckoId: "usd-coin" }],
    ["armm-v3-wxdai", "RealT RMM V3 WXDAI", "armmv3WXDAI", 18, { coingeckoId: "xdai" }],
    ["binance-coin", "Binance Coin", "BNB", 18, { coingeckoId: "binancecoin" }],
    ["bitcoin", "Bitcoin", "BTC", 8, { coingeckoId: "bitcoin" }],
    ["crv", "Curve DAO", "CRV", 18 , { coingeckoId: "curve-dao-token" }],
    ["crvusd", "crvUSD", "CRVUSD", 18 , { coingeckoId: "crvusd" }],
    ["dai", "Dai Stablecoin", "DAI", 18, { coingeckoId: "dai" }],
    ["ethereum", "Ethereum", "ETH", 18, { coingeckoId: "ethereum" }],
    ["matic", "MATIC", "MATIC", 18 , { coingeckoId: "matic-network" }],
    ["monerium-eure","Monerium EURe", "EURe", 18, { coingeckoId: "monerium-eur-money" }],
    ["pol", "POL (ex-MATIC)", "POL", 18 , { coingeckoId: "polygon-ecosystem-token" }],
    ["pond", "Marlin", "POND", 18 , { coingeckoId: "marlin" }],
    ["reg", "RealToken Ecosystem Governance", "REG", 18, { coingeckoId: "realtoken-ecosystem-governance" }],
    ["ripple", "XRP", "XRP", 6 , { coingeckoId: "ripple" }],
    ["savings-dai", "Savings Dai", "sDAI", 18, { coingeckoId: "savings-dai" }],
    ["savings-xdai", "Savings xDai", "sDAI", 18, { coingeckoId: "savings-xdai" }],
    ["solana", "Solana", "SOL", 9, { coingeckoId: "solana" }],
    ["usdc", "USD Coin", "USDC", 6, { coingeckoId: "usd-coin" }],
    ["usdt", "Tether USD", "USDT", 6, { coingeckoId: "tether" }],
    ["wbeth", "Wrapped Beacon ETH", "WBETH", 18 , { coingeckoId: "wrapped-beacon-eth" }],
    ["wbtc","Wrapped Bitcoin","WBTC" ,8 , { coingeckoId: "wrapped-bitcoin" }],
    ["weth", "Wrapped Ether", "WETH", 18, { coingeckoId: "weth" }],
    ["wsteth", "Wrapped stETH", "WSTETH", 18 , { coingeckoId: "wrapped-steth" }],
    ["xdai", "xDai", "xDAI", 18 , { coingeckoId: "xdai" }],
  ] as const;
